package com.data_management;

import java.io.IOException;
import java.nio.file.*;
import java.util.List;

/**
 * Reads patient data from files generated by FileOutputStrategy
 * and loads it into DataStorage.
 * 
 * <p>
 * In this implementation it is assumed that file 
 * output is in this format: Patient ID: <id>, 
 * Timestamp: <ts>, Label: <label>, Data: <value>
 * </p>
 */
public class FileDataReader implements DataReader {

    private final String baseDirectory;

    public FileDataReader(String baseDirectory) {
        this.baseDirectory = baseDirectory;
    }

    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        Path dirPath = Paths.get(baseDirectory);

        if (!Files.exists(dirPath) || !Files.isDirectory(dirPath)) {
            throw new IOException("Invalid directory: " + baseDirectory);
        }

        /**
         * Iterate over all files in directory
         * */
        DirectoryStream<Path> stream = Files.newDirectoryStream(dirPath, "*.txt");

        for (Path file : stream) {
            List<String> lines = Files.readAllLines(file);

            for (String line : lines) {
                try {
                    parseAndStore(line, dataStorage);
                } catch (Exception e) {
                    System.err.println("Skipping malformed line: " + line);
                }
            }
        }
    }

    /**
     * Parses a single line and stores it in DataStorage
     */
    private void parseAndStore(String line, DataStorage storage) {
        /** Split by comma **/
        String[] parts = line.split(",");

        int patientId = Integer.parseInt(parts[0].split(":")[1].trim());
        long timestamp = Long.parseLong(parts[1].split(":")[1].trim());
        String label = parts[2].split(":")[1].trim();
        String rawData = parts[3].split(":")[1].trim();

        /** Cleans data, removes % if present. **/
        rawData = rawData.replace("%", "");

        double value = Double.parseDouble(rawData);

        storage.addPatientData(patientId, value, label, timestamp);
    }
}
