package com.data_management;

import java.io.IOException;
import java.nio.file.*;
import java.util.List;

/**
 * Reads patient data from files generated by FileOutputStrategy
 * and loads it into DataStorage.
 *
 * <p>
 * This class was updated to match the new DataReader interface
 * which supports streaming. File reading is still batch-based,
 * so it runs once inside startReading().
 * </p>
 *
 * <p>
 * This keeps the system consistent while allowing both real-time
 * (WebSocket) and static (file) data sources to coexist.
 * </p>
 */
public class FileDataReader implements DataReader {

    private final String baseDirectory;

    public FileDataReader(String baseDirectory) {
        this.baseDirectory = baseDirectory;
    }

    /**
     * Starts reading data from files.
     *
     * <p>
     * Unlike WebSocketDataReader, this is not continuous.
     * It simply reads all files once and exits.
     * </p>
     */
    @Override
    public void readData(DataStorage dataStorage) {
        try {
            readAllFiles(dataStorage);
        } catch (IOException e) {
            System.err.println("Error reading files: " + e.getMessage());
        }
    }

    /**
     * Stops reading (no-op for file reader).
     *
     * <p>
     * Included to satisfy interface contract.
     * </p>
     */
    @Override
    public void stopReading() {
        // No continuous process to stop
    }

    /**
     * Reads all files in the directory and processes them.
     */
    private void readAllFiles(DataStorage dataStorage) throws IOException {

        Path dirPath = Paths.get(baseDirectory);

        if (!Files.exists(dirPath) || !Files.isDirectory(dirPath)) {
            throw new IOException("Invalid directory: " + baseDirectory);
        }

        DirectoryStream<Path> stream = Files.newDirectoryStream(dirPath, "*.txt");

        for (Path file : stream) {
            List<String> lines = Files.readAllLines(file);

            for (String line : lines) {
                try {
                    parseAndStore(line, dataStorage);
                } catch (Exception e) {
                    System.err.println("Skipping malformed line: " + line);
                }
            }
        }
    }

    /**
     * Parses a single line and stores it in DataStorage.
     *
     * <p>
     * Handles edge cases such as malformed data and percentage values.
     * This keeps parsing logic isolated (Single Responsibility Principle).
     * </p>
     */
    private void parseAndStore(String line, DataStorage storage) {

        String[] parts = line.split(",");

        if (parts.length != 4) {
            throw new IllegalArgumentException("Invalid format");
        }

        int patientId = Integer.parseInt(parts[0].split(":")[1].trim());
        long timestamp = Long.parseLong(parts[1].split(":")[1].trim());
        String label = parts[2].split(":")[1].trim();
        String rawData = parts[3].split(":")[1].trim();

        rawData = rawData.replace("%", "");

        double value = Double.parseDouble(rawData);

        storage.addPatientData(patientId, value, label, timestamp);
    }
}